### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by pinpong** [donguseo/flutter_heic_to_jpg#5]
Hi,

would be cool to seen this plugin with null safety support^^

**Comment by donguseo** [comment]
OK I will try 
thanks

**Comment by donguseo** [comment]
@percula just made a pr for this issue! 
And it looks graet to me! 
So I will merge it next week.
After merging it, I will close this issue.

**Comment by tigrenok00** [comment]
With latest version, I am getting error:

 Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:
     - package:heic_to_jpg

**Comment by percula** [comment]
@tigrenok00 , I'm guessing your dependencies aren't fully updated to match your `pubspec.yaml`. I have this issue sometimes too, where I need to run `flutter clean` and then `flutter pub get`.
